### ISSUE TITLE
Forbidden precisa estar em outro controller pra evitar redirect loop

### ISSUE THREAD

**Issue by ricardoaugusto** [luandacosta/Laravel-TodoList#1]
https://github.com/luandacosta/Laravel-TodoList/blob/master/app/Http/Controllers/TodoListController.php

Poderia estar em algo tipo ExceptionsController@usersDoesntOwnTodoList

**Comment by luandacosta** [comment]
Opa, deu certo @ricardoaugusto. 

https://github.com/luandacosta/Laravel-TodoList/commit/32997cf655182aa8a047393f04b77c78f4bb944e
